### ISSUE TITLE
Compile issues on MacOSX

### ISSUE THREAD

**Issue by hkayabilisim** [N-BodyShop/direct#1]
When compiling the codes on Mac OSX, I get the following errors:

/usr/include/rpc/xdr.h:126:3: error: type name requires a specifier or qualifier
                bool_t  (*x_getlong)(struct __rpc_xdr *, int *);
                ^

The solution that worked for me was to add "#include <rpc/types.h>" to kd.c.

**Comment by trquinn** [comment]
Can you verify that pull request #2 compiles on a Mac?
