### ISSUE TITLE
rpc vs. tirpc

### ISSUE THREAD

**Issue by teuben** [N-BodyShop/direct#3]
it seems linux (via glibc) is moving to use tirpc.   I got this to work on Ubuntu22 with the following patch to the Makefile:

      CFLAGS	=   -O -I/usr/include/tirpc
      LIBS	=   -lm -ltirpc

There was also an undefined HUGE, not sure where that is these days. I defined it, pending resolution.

PS: my patch might not work on mac.

**Comment by trquinn** [comment]
Fixed by #5
